# Generated by Django 2.1 on 2019-03-05 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainfallData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
                ('rainfall', models.FloatField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='TmaxData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
                ('t_max', models.FloatField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='TminData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
                ('t_min', models.FloatField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.DeleteModel(
            name='Weather_data',
        ),
    ]
