# Generated by Django 2.1 on 2019-03-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0002_auto_20190305_1711'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rainfalldata',
            unique_together={('year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='tmaxdata',
            unique_together={('year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='tmindata',
            unique_together={('year', 'month')},
        ),
    ]
