# Generated by Django 2.1 on 2019-03-05 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0003_auto_20190305_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rainfalldata',
            name='rainfall',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='rainfalldata',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(4000), django.core.validators.MinValueValidator(1900)]),
        ),
        migrations.AlterField(
            model_name='tmaxdata',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(4000), django.core.validators.MinValueValidator(1900)]),
        ),
        migrations.AlterField(
            model_name='tmindata',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(4000), django.core.validators.MinValueValidator(1900)]),
        ),
    ]
