# Generated by Django 2.1 on 2019-03-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0004_auto_20190305_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rainfalldata',
            old_name='rainfall',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='tmaxdata',
            old_name='t_max',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='tmindata',
            old_name='t_min',
            new_name='value',
        ),
    ]
