# Generated by Django 2.1 on 2019-03-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0005_auto_20190310_1253'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rainfalldata',
            unique_together={('year', 'month', 'country_name')},
        ),
        migrations.AlterUniqueTogether(
            name='tmaxdata',
            unique_together={('year', 'month', 'country_name')},
        ),
        migrations.AlterUniqueTogether(
            name='tmindata',
            unique_together={('year', 'month', 'country_name')},
        ),
    ]
