# Generated by Django 2.1 on 2019-03-11 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0006_auto_20190310_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='rainfalldata',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
