# Generated by Django 2.1 on 2019-03-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0007_rainfalldata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rainfalldata',
            name='date',
            field=models.DateField(),
        ),
    ]
