# Generated by Django 2.1 on 2019-03-11 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0009_auto_20190311_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rainfalldata',
            old_name='date',
            new_name='date1',
        ),
    ]
