# Generated by Django 2.1 on 2019-03-11 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0010_auto_20190311_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rainfalldata',
            name='date1',
        ),
    ]
